### ISSUE TITLE
render_html method does the same thing twice

### ISSUE THREAD

**Issue by kristiannissen** [kristiannissen/CGIRouter#2]
The render_html method performs a file read twice. Reading file content should be in a different method

**Comment by m4ddav3** [comment]
Is this not the concern of some other package? I.e. CGI::Router only cares about taking a request and telling something else to deal with it

**Comment by kristiannissen** [comment]
The CGI::Router should only take care about taking a request and tell something else to deal wih it. I thought about implementing a template package, text::template or similar, but I couldn't make up my mind and just added the render method to have some output in my browser, and yes, it's currently doing the same thing twice.
